# Generated by Django 3.0.1 on 2019-12-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191220_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votechoice',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='choice ranking'),
        ),
    ]
